version: '2'


networks:
 proxy-tier:
  external:
   name: nginx-proxy
 

services:
  mediaserver:
    image: dottgonzo/express-media-files
    ports:
      - 3001:3000
    volumes:
      - /home/dario/works/express-media-files/test/video/:/app/videofolder
      - /tmp/:/app/destfolder
    environment:
      - VIDEOFOLDER=/app/videofolder/
      - PORT=3000
      - CONVERSIONDEST=/app/destfolder
      - SERVERURI=http://localhost:3001
      - SECRET=zzzzzzzzz
      - MODE=user
    networks:
      - proxy-tier