version: '2'


networks:
 proxy-tier:
  external:
   name: nginx-proxy
 

services:
  apiauth:
    image: dottgonzo/express-media-files
    restart: always
    ports:
      - 3000:3000
    volumes:
      - /home/dario/Video:/app/videofolder
    environment:
      - VIDEOFOLDER=/app/videofolder
    networks:
      - proxy-tier
    links:
      - mongo:mongo