version: '2'


networks:
 proxy-tier:
  external:
   name: nginx-proxy
 

services:
  mediaserver:
    image: dottgonzo/express-media-files
    restart: always
    ports:
      - 3000:3000
    volumes:
      - /home/dario/works/express-media-files/test/video/:/app/videofolder
    environment:
      - VIDEOFOLDER=/app/videofolder
    networks:
      - proxy-tier